### ISSUE TITLE
There is no sound output after set prefer pipewire output

### ISSUE THREAD

**Issue by lumingzh** [neithern/g4music#1]
## Running environment
- OS: Fedora Silverblue 36
- DE: Gnome Shell 42.2
- Pipewire: 0.3.51
- APP: 0.3.0 from flathub
## Reproduce
1. open preference of G4music
2. set prefer pipewire output
3. play music
## Result
There is no sound output. However, the sound panel of gnome-control-center and notification of gnome shell showed that G4music was playing audio, but no sound.

**Comment by lumingzh** [comment]
Well, I tested many times and found this:
- only set prefer pipewire output when playing music may replay from beginning and output sound normally, but the success probability maybe only 10%
- even if success, reopen app and play music still no sound output
- if there is no sound output, turn off prefer pipewire output will always freeze the app unless not played or playing music after open app

**Comment by neithern** [comment]
不愧是gnome社区的主要中文贡献者，提的问题都这么专业，hhhh
如果可以的话，请把你微信号发我email：neithern@outlook.com

**Comment by neithern** [comment]
> Well, I tested many times and found this:
> 
> * only set prefer pipewire output when playing music may replay from beginning and output sound normally, but the success probability maybe only 10%
> * even if success, reopen app and play music still no sound output
> * if there is no sound output, turn off prefer pipewire output will always freeze the app unless not played or playing music after open app

I found pipewire and "show peak" can't work together in flatpak on Fedora 36 Workstation, but they works fine with native build, I guess maybe it is caused by different version of Gstreamer or Pipewire.

**Comment by lumingzh** [comment]
> 不愧是gnome社区的主要中文贡献者，提的问题都这么专业，hhhh 如果可以的话，请把你微信号发我email：[neithern@outlook.com](mailto:neithern@outlook.com)

不是，我啥时候成 gnome 社区的主要中文贡献者了？我也没贡献多少啊，而且我还是个懒人。

**Comment by lumingzh** [comment]
> > Well, I tested many times and found this:
> > 
> > * only set prefer pipewire output when playing music may replay from beginning and output sound normally, but the success probability maybe only 10%
> > * even if success, reopen app and play music still no sound output
> > * if there is no sound output, turn off prefer pipewire output will always freeze the app unless not played or playing music after open app
> 
> I found pipewire and "show peak" can't work together in flatpak on Fedora 36 Workstation, but they works fine with native build, I guess maybe it is caused by different version of Gstreamer or Pipewire.

你说的很对，pipewire 和 峰值显示不同时开确实没事。不过我又发现了其它问题，同时开没有音频输出的情况下，如果已经播放了几秒音乐或者音乐正在播放，不止是关闭 pipewire 输出会软件崩溃，点下一首等其它操作都会崩溃。

**Comment by neithern** [comment]
> 



> > > Well, I tested many times and found this:
> > > 
> > > * only set prefer pipewire output when playing music may replay from beginning and output sound normally, but the success probability maybe only 10%
> > > * even if success, reopen app and play music still no sound output
> > > * if there is no sound output, turn off prefer pipewire output will always freeze the app unless not played or playing music after open app
> > 
> > 
> > I found pipewire and "show peak" can't work together in flatpak on Fedora 36 Workstation, but they works fine with native build, I guess maybe it is caused by different version of Gstreamer or Pipewire.
> 
> 你说的很对，pipewire 和 峰值显示不同时开确实没事。不过我又发现了其它问题，同时开没有音频输出的情况下，如果已经播放了几秒音乐或者音乐正在播放，不止是关闭 pipewire 输出会软件崩溃，点下一首等其它操作都会崩溃。

I will try to find a better way to implement "show audio peak".

**Comment by lumingzh** [comment]
问题确认已修复。
