### ISSUE TITLE
MPRIS doesn't working with MPRIS extension

### ISSUE THREAD

**Issue by daudix-UFO** [neithern/g4music#15]
I have "mpris indicator button" extension installed, everything (MPV, Firefox, Clapper, Amberol, VLC & e.t.c) is working with it, but G4Music doesn't
# Amberol (Or any other app that support MPRIS)
![Снимок экрана от 2022-06-30 01-36-32](https://user-images.githubusercontent.com/77155297/176557337-15988b01-5f78-4a70-a8e2-ae692b0206e8.png)
# G4Music
![Снимок экрана от 2022-06-30 01-36-45](https://user-images.githubusercontent.com/77155297/176557338-6e26a07b-f5b3-4451-8297-4bb782b59983.png)
# Screencast
https://user-images.githubusercontent.com/77155297/176557052-9020ec57-f578-4ef0-afc5-fde9ababa2e1.mp4

_Sorry for horrible screencast_

**Comment by neithern** [comment]
After check hours, still not find how to work with this extension :(

**Comment by daudix-UFO** [comment]
I have no clue about coding in vala, but maybe it a vala problem?

**Comment by daudix-UFO** [comment]
I have no clue about coding in vala, but maybe it's a vala problem?

**Comment by neithern** [comment]
But this vala code works fine with the gnome standard notification area, not sure if there’s something wrong in this extension?

**Comment by TaiAurori** [comment]
Something that might be related here, [this service](https://github.com/BobbyWibowo/discordrp-mpris) crashes when G4Music launches because it can't find a "PlaybackStatus" property on its player.

**Comment by daudix-UFO** [comment]
Maybe this will be useful: [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/)
