### ISSUE TITLE
[Feature request]: Recognize folders with a single cover art

### ISSUE THREAD

**Issue by marek-lach** [neithern/g4music#16]
If there’s a file called _cover.jpg_ in a folder full of songs, load all those songs when the are selected as a playlist, each with the same one cover, which’s present in their folder.

**Comment by neithern** [comment]
cover.jpg is already be recognized as the album’s cover, didn’t work for your folders?

**Comment by neithern** [comment]
> It works, but currently folders with names (albums) are not recognised. Only individual songs. I wonder if there could be a user setting for each album folder to have it’s own one image and the rest of the songs in that one folder to be collapsable as a list?

I am no so clear about your requirement, can you please show some pictures to explain it?

**Comment by marek-lach** [comment]
In the sorting options, alongside sorting by Album, or Artist, there could also be an option to sort by _Folder_, which would sort the playlist by folder names. With audio files (songs) of each folder listed under the folder's name.

Something like... 

![IMG_20220710_162034](https://user-images.githubusercontent.com/45913977/178148895-215e532b-2c2b-4a79-8fff-2e4d058b2a2f.jpg)


This is just a feature suggestion. Thank you for making this player.

**Comment by neithern** [comment]
> In the sorting options, alongside sorting by Album, or Artist, there could also be an option to sort by _Folder_,

Do you mean your song files don't have tags (Album, artist), and the folder name is often as the album name?

**Comment by neithern** [comment]
v1.4 should be helpful.
