### ISSUE TITLE
There are no musics found after set using tracker service

### ISSUE THREAD

**Issue by lumingzh** [neithern/g4music#2]
## Running environment
- OS: Fedora Silverblue 36
- DE: Gnome Shell 42.2
- Tracker: 3.3.1
- APP: 0.2.0 from flathub
## Reproduce
1. open preference of G4music
2. set using tracker service
## Result
There are no musics displayed in playing list. I don't know if it relates to flatpak or tracker.

**Comment by neithern** [comment]
I guess it maybe caused by your tracker, it works find on my Fedora 36, you can check it with gnome-music.

**Comment by lumingzh** [comment]
> I guess it maybe caused by your tracker, it works find on my Fedora 36, you can check it with gnome-music.

但是从 flathub 安装的 gnome-music 可以正常使用。

**Comment by neithern** [comment]
> > I guess it maybe caused by your tracker, it works find on my Fedora 36, you can check it with gnome-music.
> 
> 但是从 flathub 安装的 gnome-music 可以正常使用。

I found a missing policy for tracker3, but I will remove this feature since it is slower than loading directly from a HDD.
