### ISSUE TITLE
bug: the app loads infinitely/cannot launch if an SD card is iinserted

### ISSUE THREAD

**Issue by marek-lach** [neithern/g4music#21]
I have tested this on a mobile device (the PinePhone). Sometimes, g4music even crashes the entire desktop environment. If an SD card is not present, g4music launches normally.

Sorry for being a bit vague. If there's any way for me to provide more _logs_ for you to debug the issue, let me know how to do it and I'll do it.

*Version tested*: 1.4.0

**Comment by neithern** [comment]
Try change your music location in preferences, select the music folder of the SD card.

**Comment by marek-lach** [comment]
The application cannot be launched properly, so I am unfortunately unable to change any settings. I would suspect some kind of a memory leak, or unhandled behaviour, when it comes to external storage, such as SD cards? Through I am really not sure at all why that would happen. 

Will provide some screenshots later.

**Comment by neithern** [comment]
Try eject the SD card, then launch g4music, then insert the SD, and select the music location?

**Comment by marek-lach** [comment]
> Try eject the SD card, then launch g4music, then insert the SD, and select the music location?

I am currently unable to test this, because the SD card reader on my device is right next to the battery, so I cannot both power the device and take the SD card in, or out at the same time.

However, I do have several corrupted files/songs on that SD card, and I wonder if the issue with g4music freezing/not launching is maybe because it cannot properly skip over, and doesn't know how to handle, what to do with some corrupted and unplayable songs, maybe...?

**Comment by marek-lach** [comment]
Tried without the SD card also, same launch issue, must be a problem with my desktop environment confoguration perhaps, and not the app. Through I did not have a problem launching it, before _G4music_ 1.4 came out, only since then.

Closing for now, as I am unable to provide any more information with regards to the cause...
