### ISSUE TITLE
Music stutter when I enable pipewire-audio-sinc and play videos at the same time.

### ISSUE THREAD

**Issue by laichiaheng** [neithern/g4music#22]
It doesn't happen everytime.

**Comment by neithern** [comment]
It’s a known issue, restart app may help😂

发自我的iPhone

在 2022年8月3日，11:15，小亨 ***@***.***> 写道：

﻿

**Comment by deisi** [comment]
Might be know as well, but when you skip forward multiple times within a track while pipewire sink is used, g4music can crash.
