### ISSUE TITLE
There should be a back button on headerbar of playing list panel

### ISSUE THREAD

**Issue by lumingzh** [neithern/g4music#3]
The GTK4 plus libadwaita are designed for adaptive UI that can be used on mobile device. So, I think there should be a back button on headerbar of playing list panel to let user back when the window in mobile mode, not just press Esc. And shuffle button placed in play/main panel maybe better.

Thank you.

**Comment by lumingzh** [comment]
播放列表的排序按钮依然有问题，0.4.0 版本在菜单选项前面加了单选框，但是不知道是按钮的 API 用错了还是 bug，单选框并不会显示选择的选项。

**Comment by lumingzh** [comment]
我还是建议把排序挪到播放界面，可以和重复播放功能合并改成选单，类似 lollypop 那种。播放列表上建议还是加个返回按钮。

**Comment by daudix-UFO** [comment]
这是一个很好的建议，如果我理解正确的话:)

**Comment by daudix-UFO** [comment]
Amazing!
