### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by alr86** [neithern/g4music#31]
Please add support for keyboard music control buttons to the app, this problem bothers me a lot
Edit: Use the left and right buttons to move around and add music playing time

**Comment by neithern** [comment]
I don't find how to map the "keyboard music control buttons", any other app can work in your computer? 
But the music buttons works automatically on my old MacBook.

**Comment by alr86** [comment]
> I don't find how to map the "keyboard music control buttons", any other app can work in your computer? But the music buttons works automatically on my old MacBook.

Yes, In the newer version of the G4Music With Play/Pause button on the keyboard, I can pause the music but I can't play again and I have to open the software and use G4Music Play button. Thanks for adding this feature❤️

**Comment by neithern** [comment]
I guess I already know how to fix it, please wait for the coming new version.

**Comment by alr86** [comment]
> I guess I already know how to fix it, please wait for the coming new version.

It works properly in the new version, thank you❤️
