### ISSUE TITLE
(Feature request) Discord rich presence?

### ISSUE THREAD

**Issue by pollux56** [neithern/g4music#34]
id rlly like for my music to show up under my name on discord like spotify does :) 
love the player btw :D

**Comment by pollux56** [comment]
Kinda like how resonance does it?
![Screenshot_20230410_132420](https://user-images.githubusercontent.com/81181814/230819361-8e31e94b-4d4e-4c4e-afc2-ddc97620ed28.png)

**Comment by Underdreag** [comment]
I know we can do it with discord.js-selfbot-v13 but i dont know how we can do it.
So if anybody know explain me pls 🙌.

**Comment by eiliatmr** [comment]
any progress on g4music discord rich presence?
i really hope someone makes this. 
it'll help g4music sees more attention on other platforms too.  i guarantee it

**Comment by neithern** [comment]
I found better way to implement this: Discord Rich Presence through mpris, like [this](https://github.com/FichteFoll/discordrp-mpris).

**Comment by pollux56** [comment]
> I found better way to implement this: [Discord Rich Presence through mpris](https://github.com/FichteFoll/discordrp-mpris).

Nice this looks good :)
