### ISSUE TITLE
[Feature] Sorting by disc number

### ISSUE THREAD

**Issue by intrnl** [neithern/g4music#41]
There's a big problem with albums containing two or more discs, especially in this one album where there's 8 (!) discs, which one is from disc 1? which one is from disc 4?

![image](https://github.com/neithern/g4music/assets/20620901/59b049a8-8b42-413e-91bd-8970f70caa19)

**Comment by neithern** [comment]
All the 8 (!) discs has same Album title?

**Comment by intrnl** [comment]
yes, they're all part of the same album

**Comment by tralph3** [comment]
It also creates issues while sorting. If you have multiple discs, each track of each disc resets the track number. G4music puts them next to each other. It should be:

    Disc 1 track 1 -> Disc 1 track 2 -> ... Disc 1 track 1

But currently it does:

    Disc 1 track 1 -> Disc 2 track 1
