### ISSUE TITLE
Songs not showing in playlist

### ISSUE THREAD

**Issue by yukina3230** [neithern/g4music#42]
I select some files to play but they are not showing in the playlist

![Screenshot from 2023-06-01 13-53-44](https://github.com/neithern/g4music/assets/75545944/60b6dbff-2f6b-4231-b312-2f8470ea87f3)

**Comment by neithern** [comment]
How about the new v2.0?

**Comment by yukina3230** [comment]
I am currently using the AUR package which is still on version 1.13, I will report back when it is updated to 2.0.

**Comment by yukina3230** [comment]
Wait so long so I built it myself.
Confirm this is fixed, thank you.
