### ISSUE TITLE
Cover doesn't change when between songs

### ISSUE THREAD

**Issue by yukina3230** [neithern/g4music#46]
Somehow the cover didn't change when I click Previous and Next buttons.
(The cover art of Nightwish's song still displayed right when played for the first time)

[Screencast from 2023-06-28 23-40-26.webm](https://github.com/neithern/g4music/assets/75545944/0f935be2-4c37-489e-9d72-707215837756)

**Comment by neithern** [comment]
Please try version 2.3, I have done some optimization.

**Comment by yukina3230** [comment]
Hi, I tried version 2.3, still have the issue.

[Screencast from 2023-07-01 15-28-16.webm](https://github.com/neithern/g4music/assets/75545944/cfc9f471-dab1-4933-acdd-8e023fc3d17b)

**Comment by neithern** [comment]
I see the first play delay is very long, may be related to this issue, with other players will also delay so long?

**Comment by yukina3230** [comment]
The other player I use is Rhythmbox, it doesn't have the delay.

**Comment by neithern** [comment]
Can you build yourself to test? otherwise I will upload a flatpak for you.

**Comment by yukina3230** [comment]
Yes I can build it from source, I will update with the new commit.

**Comment by neithern** [comment]
I tried to fix it, please build from the newest commit to test.😅️

**Comment by yukina3230** [comment]
It seems fixed now, the delay is shorter too, thank you. :smile:

**Comment by neithern** [comment]
👍️
