### ISSUE TITLE
lags when I rewind a song 

### ISSUE THREAD

**Issue by taske95** [neithern/g4music#47]
This is my favorite app for music, but I don't like the new update, it sometimes lags when I rewind a song (i think it is because of gapless playback, because since I turned off that option, I don't have those lag), and I also don't like the new icon design, the green color looks washed out. Thanks anyway for the hard work so far. My system is linux mint 21.1

**Comment by neithern** [comment]
In the previous versions, gapless is not REAL works, until I found and fixed recently.
So how do you "rewind a song"? Or try some other audio sink, Pipewire is stil not so good in some older system.
