### ISSUE TITLE
怀念千千静听！只想要linux下的千千静听！

### ISSUE THREAD

**Issue by yoramuhoo** [neithern/g4music#50]
怀念千千静听！只想要linux下的千千静听！

**Comment by neithern** [comment]
展开说说？

**Comment by yoramuhoo** [comment]
想要千千静听的传统界面！还可以关联lrc歌词文件，不奢求能下载歌词，歌词可以自己找。但一定要让网友知道歌词在哪里！最好可以自定义。支持常用无损音乐格式，因为以前没听过无损的，那是都是mp3，我知道以前有支持。想要各种经典的皮肤（好吧，也可以没有。）。就是完完全全复刻windowns下的千千静听。没什么好展开的，就是怀旧。就是希望原来的样子。什么现代的UI。都是垃圾。复刻出来，那将是神级。linux下，我用尽所有，均不得人意。现代的音乐播放器，还隐藏歌词文件，格式还支持不完全，这特么的什么世道？花里胡哨的，丑角人寰的。全是垃圾！千千静听的传统界面，就是永恒的经典！
