### ISSUE TITLE
Meson build fail

### ISSUE THREAD

**Issue by yukina3230** [neithern/g4music#54]
I got this error message when running `meson install -C build` with the latest commit

![image](https://github.com/neithern/g4music/assets/75545944/63133565-5877-44e9-bb54-7afc2f13ac4d)

**Comment by neithern** [comment]
Since vala v0.5.11, the factory API changed, caused this issue, but I am not sure if  this vala version is stable.

**Comment by yukina3230** [comment]
Thanks, didn't know about the API changed, I will use the flatpak version for now.

**Comment by neithern** [comment]
Fixed.
