### ISSUE TITLE
[Feature Request] Shuffle for artists

### ISSUE THREAD

**Issue by PonyLucky** [neithern/g4music#56]
Hi, I encountered meny applications and yours the faster and most intuitive. Great work.

I first though you didn't include shuffle features and then I saw #30.

The fact is that I wish to shuffle for a specific artist's songs And the click button doen't work in this case.
![image](https://github.com/neithern/g4music/assets/60187395/c148de6f-e11b-4124-a73d-0684cb8f0b22)

Therefore I ask here if you wish to include this feature. (As the shuffle algorithm already exists, it shoudn't take long).

Thank you.

**Comment by HALKRON** [comment]
I agree! A traditional shuffle button would be much more intuitive than being a different category of sort.

**Comment by neithern** [comment]
Since 4.0, you can random play an album.
