### ISSUE TITLE
Feedback on the Responsive Interface

### ISSUE THREAD

**Issue by nullstreak** [neithern/g4music#66]
Hey team, first off, I want to say I'm a big fan of your music player—really appreciate all the hard work you've put in.

I wanted to share some feedback on the responsive interface. I've noticed there's a lot of unused space that makes the album art appear quite small. It'd be great to have larger artwork for a better visual experience.

[output.webm](https://github.com/neithern/g4music/assets/139914347/fd67e064-6451-47d5-a5ad-6d9824e43631)

Also, the multi-column playlist doesn't seem to hit the right note for me. It feels a bit cluttered and takes away from the simplicity of browsing my music.

Hope this helps, and thanks again for an awesome music player!

**Comment by neithern** [comment]
Please check this issue: https://gitlab.gnome.org/neithern/g4music/-/issues/98
