### ISSUE TITLE
Center Player In View

### ISSUE THREAD

**Issue by ToxicPine** [neithern/g4music#7]
Please vertically center the player in the right pane, Amberol has it centered in the manner I am suggesting.

Currently, if you expand the window, the player will float to the top. This will leave a lot of space below the player, which is visually awkward.

I've attached images that demonstrate the difference.

![G4Music](https://user-images.githubusercontent.com/99731180/174471290-1ee722b6-0b25-4144-a6da-5ecb8747adab.png)
![Amberol](https://user-images.githubusercontent.com/99731180/174471302-32c61ab4-65ba-48b9-9886-98ba74f4dd64.png)

Thank you for your time!

**Comment by neithern** [comment]
![big-cover-fs8](https://user-images.githubusercontent.com/3124960/174472894-15f751fc-5801-412e-8f5e-b276720760e2.png)
How about this one.
