### ISSUE TITLE
Always asks to import music.

### ISSUE THREAD

**Issue by shresth-kumar-lal** [neithern/g4music#72]
Every once in a while 'add music folder' shows up even when there is no changes in files . Then the folder has to be added manually.

latest flatpak version.

**Comment by neithern** [comment]
Please refer this: https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory#:~:text=The%20specific%20command%20you%20need%20is%20%28it%20may,suffix%22%2C%20just%20put%20the%20path%20part%20in%20quotes.
