### ISSUE TITLE
[Bug] Window titlebar buttons are configured to the left, they show up in duplicate.

### ISSUE THREAD

**Issue by erenfro** [neithern/g4music#80]
When using Tweaks->Windows->Titlebar Buttons, Placement = Left, titlebar buttons show up in duplicate as shown in the screenshot:
![Screenshot from 2024-06-09 00-37-00](https://github.com/neithern/g4music/assets/1180990/bdb7b41f-19c3-4e2c-a4ea-22f571457731)

When configured to the right, it's normal, non-duplicated:
![Screenshot from 2024-06-09 00-39-49](https://github.com/neithern/g4music/assets/1180990/f265b3e1-36af-4cce-b3f0-1c93d0a727b8)

**Comment by neithern** [comment]
Fixed in v3.7

**Comment by erenfro** [comment]
> Fixed in v3.7

Awesome! Thank you for looking into this!
