### ISSUE TITLE
AAC files don't have a thumbnail in notifications

### ISSUE THREAD

**Issue by bkmnst** [neithern/g4music#83]
All AAC encoded files (.m4a) don't have a thumbnail in the notifications.

![Screenshot from 2024-06-26 21-42-56](https://github.com/neithern/g4music/assets/49692481/fa302678-d5c8-4256-a727-e6be227a5d21)

 OPUS, FLAC and MP3 files don't have this problem.

![image](https://github.com/neithern/g4music/assets/49692481/7e7b9fca-e9db-4c5f-801a-cd7f829e728e)

 Tried different files and encoders, and issue still persists. Other music players don't have this problem.

**Comment by neithern** [comment]
please upload this m4a file for testing.

**Comment by bkmnst** [comment]
sure! 
[m4a.zip](https://github.com/user-attachments/files/15997493/m4a.zip)

**Comment by neithern** [comment]
Fixed in v3.7.1
