### ISSUE TITLE
[BUG] Window resizing on flatpak build is very jittery and laggy compared to build from source

### ISSUE THREAD

**Issue by FriendlyNeighbourhoodWatch** [neithern/g4music#84]
When dragging mouse around the edges to resize the windows, the source build is smooth while the flatpak build lags behind a lot and is very slow, but I can see no other noticeable differences and the animations seem smooth on both other than that. 

https://github.com/neithern/g4music/assets/174258261/f1bab6b9-2b95-45d9-8184-1b8ec8928254

https://github.com/neithern/g4music/assets/174258261/b264c9dd-9ba0-4ac3-9cdd-064b8dbe431f

**Comment by neithern** [comment]
I guess missing some package like 'org.freedesktop.Platform.GL.default', or you may test some other GTK4 apps?

**Comment by FriendlyNeighbourhoodWatch** [comment]
It also occurs with some other gtk4 apps like Cartridges but not all
I think it may be some dependency issue but not sure what. Can you reproduce?

**Comment by neithern** [comment]
I can't reproduce with 'org.freedesktop.Platform.GL.default' (ver 24.1.3, branch 23.08-extra), I still guess GPU-acceleration is not work in your flatpak system.

**Comment by FriendlyNeighbourhoodWatch** [comment]
Okay. I have tried installing that branch and it still does not work.

**Comment by neithern** [comment]
😂 try set "Background blur mode" to "Never"?

**Comment by FriendlyNeighbourhoodWatch** [comment]
Done. No effect, marginally smoother but not to a significant degree and still extremely bad

**Comment by neithern** [comment]
How about v3.9?

**Comment by FriendlyNeighbourhoodWatch** [comment]
Yes, definitely smoother and more usable, but still quite a bit laggier and less smooth than native.
