### ISSUE TITLE
Are playlists supported by this application?

### ISSUE THREAD

**Issue by kazemaksOG** [neithern/g4music#85]
Hi!

I just found this application and it visually looks amazing! Only problem i face is that it seems that there is no playlists tab. From the screenshots of the app it seems that its suppose to be there, but I can't tell, since the feature is not specifically mentioned anywhere.

I am using arch linux with wayland (Hyprland).

I installed the app both from flatpak and manually built it, both cases, this is the top bar:
![image](https://github.com/neithern/g4music/assets/59805622/be6944f1-9a0a-4169-ac62-421bdae5bfae)

**Comment by neithern** [comment]
If you have .m3u or .pls playlist file, they will be displayed in the tab "Playlist".
