### ISSUE TITLE
Bounty: Playlist editing support

### ISSUE THREAD

**Issue by boredsquirrel** [neithern/g4music#86]
https://gitlab.gnome.org/neithern/g4music/-/issues/36#note_2164241

I used like all Music Players on Flathub and G4Music is by far the best one. I would offer a bounty for write-to-playlist support.

- adding tracks to a playlist file
- creating a playlist
- deleting a playlist
- renaming a playlist

I would offer 50€ for this

**Comment by neithern** [comment]
Playlists are full supported in v4.0, please check it, thanks!
