### ISSUE TITLE
[PO] .pot and .po generation is not working for me

### ISSUE THREAD

**Issue by Penfore** [neithern/g4music#87]
I'm not experienced with generating this files or using meson in general.

I tried following the `UPDATE.md` file inside the `/po` folder, but I get the message:

`ERROR: Current directory is not a meson build directory: /{path}/g4music/po.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.`

I also tried on the root of the application, but I still got the error:

`ERROR: Current directory is not a meson build directory: /{path}/g4music.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.`

My goal is to update the `pt_BR.po` file so I can update translation.

Thank you!

**Comment by neithern** [comment]
Please update translation to: https://l10n.gnome.org/module/g4music/, thanks!
