### ISSUE TITLE
[PO] Error when submitting file to l10n.gnome.org

### ISSUE THREAD

**Issue by Penfore** [neithern/g4music#88]
I have updated the translation for Brazilian Portuguese downloading and editing the file present in [this link](https://l10n.gnome.org/vertimus/g4music/master/po/pt_BR/), but I got the following error:

![image](https://github.com/user-attachments/assets/ecdb555b-bb54-47d4-9e1e-c48b96012e79)

which translates to:

`The .po file failed the “msgfmt -vc” test. Please fix it and try again.`

Any idea of how I can proceed? 

Thank you!

**Comment by neithern** [comment]
You'd better edit the po file with gtranslator.

**Comment by Penfore** [comment]
I have used gtranslator


Enviado do meu Galaxy



-------- Mensagem original --------
De : Nanling Zheng ***@***.***>
Data: 31/07/2024 22:01 (GMT-03:00)
Para: neithern/g4music ***@***.***>
Cc: Fulvio Leo ***@***.***>, Author ***@***.***>
Assunto: Re: [neithern/g4music] [PO] Error when submitting file to l10n.gnome.org (Issue #88)


You'd better edit the po file with gtranslator.

**Comment by neithern** [comment]
Please run 'msgfmt -vc pt_BR.po' to see what's wrong with the po file.

**Comment by Penfore** [comment]
There was a line `msgctxt "shortcut window"` commented with `#|` causing a syntax error. 
I removed the tag `#|`, submitted the file again and it worked. 

Thank you very much!
