### ISSUE TITLE
sub menus flash and jitter

### ISSUE THREAD

**Issue by TechyTrickster** [neithern/g4music#89]
whenever i open up a sub menu, like for volume or a context menu with right click, the sub menu will flash at a low frequency (at about 1 or 2 hz) if there are any screen updates happening in the window, like for the spinning album art or the vu meter. when music is playing  Though, if nothing is moving, mousing over and changing the highlight state of a menu doesn't seem to count as an update for the purposes of this issue.  But, moving the volume slider does.  Its mild annoyance, but for me its starkly highlighted since its the ONLY problem i've come across.

**Comment by TechyTrickster** [comment]
update to the issue.  if i try to change the volume using the app control while music is playing, the app crashes.  it does not crash if the music is paused while i'm using the volume slider.  So this is a bit more serious, now.

**Comment by neithern** [comment]
Any other platform info?

**Comment by Xornent** [comment]
> whenever i open up a sub menu, like for volume or a context menu with right click, the sub menu will flash at a low frequency (at about 1 or 2 hz) if there are any screen updates happening in the window, like for the spinning album art or the vu meter. when music is playing Though, if nothing is moving, mousing over and changing the highlight state of a menu doesn't seem to count as an update for the purposes of this issue. But, moving the volume slider does. Its mild annoyance, but for me its starkly highlighted since its the ONLY problem i've come across.

Having the same issue. But I found the flashes and jitters occur only when the music is playing (no matter I turn on the spinning of the album art or not). If the music is stopped, all these flashes go away.

Running on Fedora 40 with GNOME 46. Build from source.

**Comment by TechyTrickster** [comment]
> Any other platform info?

my apologies!
![image](https://github.com/user-attachments/assets/14fa0948-74e7-47d8-9503-b003d35b613c)

**Comment by neithern** [comment]
Looks like gnome 42 released 2 years ago is too old, you'd better upgrade to 46.

**Comment by Winterhuman** [comment]
This seems to be the same issue as https://github.com/neithern/g4music/issues/60. I'm using XFCE 4.18.4 (Linux 6.10.4), so it's not a Gnome specific issue at least.

Interestingly, me and @TechyTrickster both have 1440p displays it seems; I wonder if that's (and maybe the DPI set) is the common factor for reproducing this.

**Comment by TechyTrickster** [comment]
i'm actually learning gtk 4, right now.  maybe in a few weeks i could take a look at the code base and try to pin down what the issue could be.

**Comment by Winterhuman** [comment]
Gapless v3.9 (Flatpak) has fixed the volume bar shaking for me. @TechyTrickster does that version fix things for you as well?
