### ISSUE TITLE
Adjust Padding

### ISSUE THREAD

**Issue by ToxicPine** [neithern/g4music#9]
As you can see from the attached screenshots, Amberol has less padding between lines in the sidebar, so they sit closer together, compared to G4Music.
Can we have the padding in G4Music as it is in Amberol, please?

![Amberol](https://user-images.githubusercontent.com/99731180/174471974-2f8821b1-6bd9-44f1-abaf-0172d8db66f3.png)
![G4Music](https://user-images.githubusercontent.com/99731180/174471975-63857868-892a-4af7-98fa-3c7b3cde5f7a.png)

**Comment by neithern** [comment]
Sorry, but I am not going to clone Amberol.
