### ISSUE TITLE
Album art doesnt load in kde properly if the song auto plays.

### ISSUE THREAD

**Issue by LittleLilyBun** [neithern/g4music#90]
If a song auto plays due to the previous song ending, KDE Plasma's Media widget doesn't show the album art correctly, clicking on the song or using the next/previous keys loads album art correctly.

Example of clicking or using next/previous keys:
![image](https://github.com/user-attachments/assets/24e205ed-fad4-4c38-a014-a5df2779fa52)

Example of a song auto playing:
![image](https://github.com/user-attachments/assets/0df77c61-c55c-4596-8942-17866eb1ffe9)

I'm using Version 3.8.1 from Flathub.

**Comment by Mnky313** [comment]
I'm having a similar issue where the loaded artwork is 1 song behind when letting it auto play, seems somewhat related. 
Hyprland + Flatpak 3.8.2

![image](https://github.com/user-attachments/assets/af156824-8629-4f88-a3a4-d41d923f0bb3)
![image](https://github.com/user-attachments/assets/0ae9681e-7cef-4a1d-bbce-168611b21090)

**Comment by neithern** [comment]
Fixed in v3.9.

**Comment by thepragmaticmero** [comment]
Mr. Kms? omg so mood
