### ISSUE TITLE
Using the Pipewire Gstreamer Sink option creates microstutters

### ISSUE THREAD

**Issue by thepragmaticmero** [neithern/g4music#93]
Ok hear me out. First world problem is about to be described.

Everything fine with normal music playing. The problem arises when I for example open another firefox youtube tab and sound starts playing. My main music stops for a fraction of a millisecond, and then keeps playing like normal. It only happens sometimes tho. Changing the Sink to **Pulseaudio** solves the problem. Is there an "advantage" of using the pipewire sink? I can't hear it at all but I feel better using a new and shiny protocol, ya know, for the future. I'm a wayland, rust, pipewire, archbtw shill you know.

I rlly like this project, like Jesse Pinkman said: "Its the bomb"

Tip 4 noobs: Use [Easy Effects](https://flathub.org/apps/com.github.wwmm.easyeffects) with equalizers and an [AutoEq](https://autoeq.app/) preset matching your headphones, the sound is amazing using an Eq on pipewire :D

**Comment by neithern** [comment]
Pipewire has lower latency, but as as gstreamer;s audio sink, it doesn't seem to be very stable yet, because it's Rank is None.
