### ISSUE TITLE
Feature request: use ORIGINALDATE instead of DATE for FLAC files

### ISSUE THREAD

**Issue by waltmck** [neithern/g4music#94]
Thank you for the beautiful music player, I use it every day!

Music metadata is poorly standardized, but it seems that both Lidarr and MusicBrainz Picard use ORIGINALDATE for original release dates and DATE for reissue dates. Many of my albums managed by Lidarr only have ORIGINALDATE set with DATE empty, and even for the rest I think that showing original release date would be preferable to showing reissue date (i.e., "90s music" typically means music originally released in the 90s rather than remastered Beatles albums). This is the default behavior of my other music player, Auxio on Android.

**Comment by neithern** [comment]
Can you please send me a file for parsing?

**Comment by waltmck** [comment]
Sure! To avoid copyright issues, I copied metadata from files in my actual library onto a public-domain FLAC file using the following command:
```
metaflac --export-tags-to=- input.flac | metaflac --remove-all-tags --import-tags-from=- output.flac
```

[Here](https://waltmckelvie.com/files/shows-no-date.flac) is a file that shows no date on G4music, since it has only ORIGINALDATE. [Here](https://waltmckelvie.com/files/shows-rerelease-date.flac) is a file that shows the date of the reissue, since it has both DATE (the reissue date) and ORIGINALDATE (the original release date).

Let me know if you need anything else!

**Comment by neithern** [comment]
Will be supported in the coming new version, thanks for your help.

**Comment by neithern** [comment]
Supported in v4.0, please check it, thanks!

**Comment by waltmck** [comment]
I checked it and it works wonderfully, thank you!
