### ISSUE TITLE
Playlist synchronization troubles with some apps - absolute/relative Paths

### ISSUE THREAD

**Issue by nicolasmol** [neithern/g4music#95]
Hi there.
First of all, a lot of thanks for the playlist editing feature addition.
Here are the first bugs.

**Below is an example of a .m3u playlist generated by an Android app (Muzio Player)**
```
#EXTM3U
#EXTINF:334669,Ronny Jordan - My Favourite Things
/storage/emulated/0/Music/Ronny Jordan - My Favourite Things (Lifestyle2 - Bar Jazz Vol 1 (International Version)).m4a
#EXTINF:301560,Trentemøller - Even Though You're with Another Girl
/storage/emulated/0/Music/Trentemøller - ... Even Though You're with Another Girl.mp3
```

Now first of all, the problem that was okay and I managed to resolve is that it there was absolute path. It's not a real problem because I managed to create a Linux symbolic link.

So let's analyse the problems with this fixed one:

```
#EXTM3U
#EXTINF:334669,Ronny Jordan - My Favourite Things
Ronny Jordan - My Favourite Things (Lifestyle2 - Bar Jazz Vol 1 (International Version)).m4a
#EXTINF:301560,Trentemøller - Even Though You're with Another Girl
Trentemøller - ... Even Though You're with Another Girl.mp3
```

But now here is what happened to this playslist when I add a music from your app:

```
#EXTM3U
#PLAYLIST:Chillout
#EXTINF: ,Ronny Jordan - My Favourite Things
Ronny Jordan - My Favourite Things (Lifestyle2 - Bar Jazz Vol 1 (International Version)).m4a
#EXTINF: ,Trentemøller - Even Though You're with Another Girl
Trentemøller - ... Even Though You're with Another Girl.mp3
**#EXTINF: ,neverlost
neverlost.mp3**

```

So as you can see, I don't know what is the purpose of those numbers maybe some IDS..? But they disappear.
So the playlist is not usable again in the Android application (using Syncthing).

 Do you know about this ID? Is that specific to this Android application ?
[EDIT: got the answer just after thx to GhatGPT: No they are not ! ]

 Maybe yes but at least could you avoid removing them ?
 
 
### BELLOW ARE THE FIRST SUGGESTIONS FROM CHATGPT:

Hi again,

After analyzing the issue, here's some additional information that may help in diagnosing the problem:

**Missing #EXTINF fields:**
The M3U format uses the #EXTINF tag to store extra information about each track, particularly the duration in milliseconds (the number before the comma) and the track title. For instance, the line #EXTINF:334669,Ronny Jordan - My Favourite Things means that the track lasts 334,669 milliseconds (around 5 minutes and 34 seconds) and has the title "Ronny Jordan - My Favourite Things."

In the playlist modified by G4Music, the durations (the numbers before the comma) are missing, leaving only the title with an empty duration (#EXTINF: ,Ronny Jordan - My Favourite Things).

**Possible cause of the issue:**
It seems that G4Music may not handle the track duration information correctly when editing or adding tracks to an M3U file. Some applications, like Muzio Player on Android, rely on these durations to properly read and manage playlists, and the absence of these numbers might render the playlist unusable in such apps. G4Music might not fully support managing all metadata associated with tracks, particularly the time information in #EXTINF.

**Are these IDs specific?**
The numbers in #EXTINF aren’t really "IDs" but are simply durations in milliseconds. This format is used by most M3U-compatible music players. If these values are removed, it can cause issues in apps that depend on this information to properly read or play audio files. Since Muzio Player seems to need these durations, their absence could explain why the playlist doesn't work there after being edited by G4Music.

**Potential solution:**
A temporary fix would be to manually restore the durations in the M3U file, but that’s not a practical long-term solution. Ideally, G4Music should preserve this information when modifying or adding tracks. You could consider implementing a feature to keep the #EXTINF values intact when editing a playlist, or at least avoid removing them if they are already present.

In summary, the issue seems to be that G4Music doesn’t save or preserve track durations in the #EXTINF tags. This feature is important for certain apps like Muzio Player, and it would be helpful if G4Music could avoid erasing this data.

Thanks again for your work!

**Comment by neithern** [comment]
ChatGPT answered exactly, it's true that G4Music doesn't keep track duration, that's because the lack of duration shouldn't cause some players to fail to load the playlists, even if the whole #EXTINF is missing it's not a problem, I've tested some players on Linux and they all work fine.
The problem now, as you can see, is that G4Music doesn't show the duration in the list, because parsing the duration of some VBR MP3 files is not guaranteed to be accurate, and there are no plans to parse the duration from the files and use it.
So, let's see if we can suggest Muzio Player to be compatible with this problem (maybe not a reasonable suggestion😂).

**Comment by nicolasmol** [comment]
Thanks a lot for your prompt answer maybe the first thing is just to keep the duration that already exists as a first workaround. After, I don't know if the duration must be very precise even for Muzio player. Surely it's only a matter of missing field. What do you think ?

**Comment by neithern** [comment]
> I don't know if the duration must be very precise even for Muzio player.
So any other player can’t work without the duration?

**Comment by nicolasmol** [comment]
Okay, sorry no the problem was not about the missing duration that about the absolute path which was missing:

This is okay for Muzio Player:

```
#EXTM3U
#PLAYLIST:Chillout
#EXTINF: ,Ronny Jordan - My Favourite Things
/storage/emulated/0/Ronny Jordan - My Favourite Things (Lifestyle2 - Bar Jazz Vol 1 (International Version)).m4a
#EXTINF: ,Trentemøller - Even Though You're with Another Girl
/storage/emulated/0/Trentemøller - ... Even Though You're with Another Girl.mp3
**#EXTINF: ,neverlost
/storage/emulated/0/neverlost.mp3**
```

**Comment by neithern** [comment]
> So what can I suggest to you is only to add an option to preserve the absolute path or not


If you save the playlist at the same parent folder of the music files, it will be relative path.

**Comment by nicolasmol** [comment]
Also keep in mind that I was obliged to do this on my PC:

`sudo ln -s $HOME/Musiques /storage/emulated/0/Music    `

**Comment by nicolasmol** [comment]
> > So what can I suggest to you is only to add an option to preserve the absolute path or not
> 
> If you save the playlist at the same parent folder of the music files, it will be relative path.

oh okay so I'm gonna manage to save the playlists in a sub-folder to try it now. I'll be back to you in a few minutes

**Comment by nicolasmol** [comment]
Okay perfect you were exactly right. The solution is to put the playlist in a different (subf)older.
Thanks again for support.
