### ISSUE TITLE
Flatpak doesn't start.

### ISSUE THREAD

**Issue by LittleLilyBun** [neithern/g4music#96]
After updating to v4.0, running the flatpak doesn't seem to work, starting via the terminal shows this error: `Gdk-Message: 14:38:14.405: Error 71 (Protocol error) dispatching to Wayland display.`

Edit: tested an older version by using `sudo flatpak update --commit=97f41c48eb81f863e0b329406f8227f13bf6423998bc32317a83546621e03c06 com.github.neithern.g4music` and the app runs fine, so it seems to be caused by something in v4.0, my bets are on the switch to GNOME 47.

**Comment by neithern** [comment]
If you’re nvidia user, check this issue with gtk 4.16: https://gitlab.gnome.org/GNOME/gtk/-/issues/7015
